DEVDOCS-4634: [add] Orders V2 Update a Order's GC Consignment
bigcommerce/api-specs pull request #1103
Opened 2022-12-27 23:00 UTC by bc-tgomez

# [DEVDOCS-4634]

## What changed?
* Add GC consignment support for Update an Order.

## Anything else?
Related PRs: https://github.com/BC-SEven/api-specs/tree/ORDERS-4981

2022-12-28 15:44 UTC, stanzikratelbc approved these changes
LGTM

2022-12-30 17:48 UTC, bc-traciporter reviewed
Hi Tina, The example looks good but I did not see changes to the definition. Perhaps it was in a different PR. I think consignment should be there along with definitions for quantity (must be 1 or 0) and recipient_email (emails should match gc recipient email). In addition,  it says "Also support adding new gift-certificate line item to existing consignment, or adding new gift-certificate consignments." I think this should be in the specification.

2023-01-17 07:48 UTC, slsriehl requested changes
Please address Traci's comments.

2023-01-17 07:49 UTC, slsriehl commented on reference/orders.v2.oas2.yml
> +              Updating an Order's Gift Certificate Consignment:
```suggestion
              Updating an Orderʼs Gift Certificate Consignment:
```
otherwise we'll run into linting errors going forward

2024-01-10 21:31 UTC, bc-tgomez commented
Closing branch as it now lives in the [Docs repo](https://github.com/bigcommerce/docs/pull/35).

2024-01-10 21:32 UTC, closed without merging