updated amount definition
bigcommerce/api-specs pull request #1108
Opened 2022-12-29 20:09 UTC by bc-traciporter

# [DEVDOCS-4684]

## What changed?
changed the definition of amount

## Anything else?
Related PRs, salient notes, etc

2022-12-30 15:47 UTC, bc-tgomez commented on reference/catalog.v3.yml
> +            The discount can be a fixed dollar amount or a percentage. For a fixed dollar amount enter it as an number and the response will return as an number. For percentage enter the amount as th
```suggestion
            The discount can be a fixed dollar amount or a percentage. For a fixed dollar amount enter it as a number and the response will return as a number. For percentage, enter the amount as the percentage divided by 100 using string format. The response will return in decimal format. For example, 10% percent would be “.10”.
```

2022-12-30 21:56 UTC, slsriehl commented on reference/catalog.v3.yml
> +            The discount can be a fixed dollar amount or a percentage. For a fixed dollar amount enter it as an number and the response will return as an number. For percentage enter the amount as th
```suggestion
            You can express the discount as either a fixed dollar amount or a percentage. To use a fixed dollar amount, send a number; the response will return a number. To use a percentage, divide the percentage by 100 and send the result in string format. For example, represent 10% as “.10”. The response will return a float.
```

2022-12-30 21:57 UTC, slsriehl commented on reference/catalog.v3.yml
> +          type: number
this should be number or string.

2022-12-30 22:03 UTC, slsriehl requested changes
1. This entry occurs twice in the spec file, and this schema is used in several larger schemas. Because the datatypes, required fields, etc, are quite different depending on whether the bulk pricing rule is part of a request or response, I recommend paring this down and defining the request and the response separately using allOf. If we don't represent this complexity, we'll keep getting tickets.
2. The ticket has another ask, which is to revise the `quantity_min` property.

Thanks for the work, everyone.

2023-01-06 15:12 UTC, bc-traciporter commented
@bc-andreadao @slsriehl  recommends having different schemas for requests and responses for Product Bulk Pricing Rules endpoints and the other Catalog endpoints as well. I know you have a PR that changes the structure for many of these endpoints. I would like to wait until your PR goes through first before sending this PR though.

2023-01-06 18:02 UTC, bc-andreadao commented
> @bc-andreadao @slsriehl recommends having different schemas for requests and responses for Product Bulk Pricing Rules endpoints and the other Catalog endpoints as well. I know you have a PR that changes the structure for many of these endpoints. I would like to wait until your PR goes through first before sending this PR though.

@bc-traciporter Yeah my [PR 1101](https://github.com/bigcommerce/api-specs/pull/1101) changes the catalog api endpoints so that request and responses have the correct schema. Just bumped it for final review

2023-01-19 19:36 UTC, slsriehl commented
FYI @bc-traciporter 1101 has been merged to staging.

2023-01-21 00:03 UTC, slsriehl commented on reference/catalog.v3.yml
> +                          The minimum inclusive quantity of a product to satisfy this rule. Must be greater than or equal to zero. For `fixed` rules, the minimum quantity can't be less than two.
replace this single straight quote with an apostrophe character.

2023-01-21 00:24 UTC, slsriehl commented on reference/catalog.v3.yml
> +            You can express the discount as either a fixed dollar amount or a percentage. To use a fixed dollar amount, send a number; the response will return a number. To use a percentage, divide t
we have 3 types of discount amount, and it's not clear to me whether the fixed dollar amount expresses price discounts or fixed discounts.

2023-03-24 19:45 UTC, merged