DEVDOCS-4670: [update] carts.v3.yml, add cart metafield endpoints
bigcommerce/api-specs pull request #1132
Opened 2023-01-18 20:48 UTC by bc-traciporter

# [DEVDOCS-4670]

## What changed?
Added cart metafield endpoints

## Anything else?
Related PRs, salient notes, etc

2023-01-23 16:45 UTC, becomevocal requested changes
Two things that would make this ready-to-go:
- `cart_id` needs to be listed as a string type. It's currently listed as an integer a few times in this PR. It's a string because they reference the UUID of the cart.
-  "The ID of the `Metafield` to which the transactions belong" as the description of `metafield_id` doesn't sound completely accurate? Because transactions aren't intimately attached to metafields. Simplifying this to "The unique ID of the `Metafield`" would be more accurate.

2023-01-26 16:27 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |Value|Description
```suggestion
            | Value | Description |
```

2023-01-26 16:27 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |-|-|
```suggestion
            | :--- | :--- |
```
I think we've been doing this for our tables

2023-01-26 16:28 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`app_only`|Private to the app that owns the field|
```suggestion
            | `app_only` | Private to the app that owns the field. |
```

2023-01-26 16:29 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`read`|Visible to other API consumers|
```suggestion
            | `read` | Visible to other API consumers. |
```

2023-01-26 16:29 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`write`|Open for reading and writing by other API consumers|
```suggestion
            | `write` | Open for reading and writing by other API consumers. |
```

2023-01-26 16:30 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`read_and_sf_access`|Visible to other API consumers, including on storefront|
```suggestion
            | `read_and_sf_access` | Visible to other API consumers, including on storefront. |
```

2023-01-26 16:36 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |Value|Description
```suggestion
            | Value | Description |
```

2023-01-26 16:37 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |-|-|
```suggestion
            | :--- | :--- |
```
I believe we've been doing this for our tables

2023-01-26 16:37 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`app_only`|Private to the app that owns the field|
```suggestion
            | `app_only` | Private to the app that owns the field. |
```

2023-01-26 16:37 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`read`|Visible to other API consumers|
```suggestion
            | `read` | Visible to other API consumers. |
```

2023-01-26 16:37 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`write`|Open for reading and writing by other API consumers|
```suggestion
            | `write` | Open for reading and writing by other API consumers. |
```

2023-01-26 16:38 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`read_and_sf_access`|Visible to other API consumers, including on storefront|
```suggestion
            | `read_and_sf_access` | Visible to other API consumers, including on storefront. |
```

2023-01-26 16:38 UTC, bc-andreadao commented on reference/carts.v3.yml
> +            |`write_and_sf_access`|Open for reading and writing by other API consumers, including on storefront|
```suggestion
            | `write_and_sf_access` | Open for reading and writing by other API consumers, including on storefront. |
```

2023-01-26 16:40 UTC, bc-andreadao reviewed
added table markdown suggestions

2023-01-31 07:46 UTC, slsriehl commented on reference/carts.v3.yml
> +openapi: 3.0.3
```suggestion
openapi: '3.0.3'
```

string type per oas spec

2023-01-31 22:24 UTC, slsriehl approved these changes
this was a lot of work. well done!

2023-01-31 22:26 UTC, merged