Remove required fields for update customer API
bigcommerce/api-specs pull request #1211
Opened 2023-03-10 17:22 UTC by kzhang-dsg

# [DEVDOCS-] N/A
The update customer API does not have any required fields. It is incorrectly documented in the API spec and on the website.

## What changed?
* Removed the required fields for the update customer API (the customer_Put model)
* Moved the customer_Put model under the schema definations

## Anything else?
N/A

2023-04-11 17:12 UTC, bc-tgomez requested changes
Looks great! Just a few editorial suggestions.

2023-04-11 17:12 UTC, bc-tgomez commented on reference/customers.v2.yml
> +          description: 'If the customer accepts product review emails or abandon cart emails. Read-Only. '
```suggestion
          description: 'If the customer accepts product review emails or abandon cart emails. Read-Only.'
```

2023-04-11 17:12 UTC, bc-tgomez commented on reference/customers.v2.yml
> +          description: 'If applicable, the tax-exempt category of the shopper’s customer account. You can apply a tax-exempt category to multiple customers. This code should match the exemption codes
```suggestion
          description: 'If applicable, the tax-exempt category of the shopper’s customer account. You can apply a tax-exempt category to multiple customers. This code should match the exemption codes provided by the third-party integration.'
```

2023-12-21 20:05 UTC, slsriehl approved these changes

2023-12-21 20:08 UTC, merged