Rename `url` to `custom_url` in Category Model
bigcommerce/api-specs pull request #1299
Opened 2023-05-02 21:17 UTC by kzhang-dsg

According to the APi response, the `url` property should be `custom_url` for Category Model

2023-05-03 17:18 UTC, bc-traciporter commented
@kzhang-dsg Thank you for submitting this PR.  The line you indicated refers to a model that is not called in the specification file. Changing this line would not change what is displayed in our developer docs.

2023-05-03 17:31 UTC, bc-traciporter commented
@kzhang-dsg After looking at it again, you are correct.  We will merge your changes.

2023-05-03 17:31 UTC, bc-traciporter approved these changes
LGTM

2023-05-09 20:37 UTC, slsriehl requested changes
@kzhang-dsg Until we dedupe the new Catalog files, we have repeated schemas. Please make these changes in the `category-trees_catalog.v3.yml` file as well.

2023-05-17 16:54 UTC, bc-traciporter commented
@slsriehl I updated the `categories-trees_catalog.v3.yml file. Can you review it?

2023-05-17 17:25 UTC, slsriehl commented on reference/catalog.v3.yml
> +            custom_url:
```suggestion
            url:
```

revert

2023-05-17 17:26 UTC, slsriehl commented on reference/catalog.v3.yml
> +        url:
```suggestion
        path:
```
revert for read-only file

2023-05-17 17:32 UTC, slsriehl commented
Due to limitations with editing a fork branch and the size of the old catalog file, i'm merging this to a local feature branch so we can revert changes to the read-only file.

2023-05-17 17:33 UTC, merged

2023-05-17 17:36 UTC, bc-traciporter commented
Thanks @slsriehl