DEVDOCS-4932: [revise] Customers V3, update email `maxlimit` in customer_Post schema
bigcommerce/api-specs pull request #1394
Opened 2023-07-26 21:24 UTC by bc-tgomez

# [DEVDOCS-4932]

## What changed?
Provide a bulleted list in the present tense
* 

## Anything else?
Add related PRs, salient notes, ticket numbers, etc.

ping {names}

2023-08-28 17:37 UTC, slsriehl approved these changes

2023-08-28 17:39 UTC, slsriehl commented on reference/customers.v3.yml
> +          maxLength: 85
```suggestion
          maxLength: 250
```

2023-08-28 17:41 UTC, slsriehl requested changes
update to reflect limit from @bc-akshatkaushik on Customers

2023-08-28 17:42 UTC, slsriehl approved these changes

2023-08-29 01:19 UTC, bc-akshatkaushik submitted a review, later dismissed
Changes look good to me 👌

2023-12-20 21:32 UTC, closed without merging

2023-12-20 21:32 UTC, bc-tgomez commented
Dropping branch as work is outdated.