DEVDOCS-3762-add-discount-to-checkout
bigcommerce/api-specs pull request #732
Opened 2022-04-12 18:04 UTC by traci707

# [DEVDOCS-3762](https://jira.bigcommerce.com/browse/DEVDOCS-3762)

## What changed?
Added new endpoint, v3/checkouts/{checkoutId}/discounts

2022-04-12 23:47 UTC, valentindellangela commented on reference/checkouts.v3.yml
> +                        id:
This api only accepts `discounted_amount` and `name` in the payload.

2022-04-12 23:48 UTC, valentindellangela commented on reference/checkouts.v3.yml
> +        Adds a discount to an existing *checkout*.
Maybe we can add that this discount only applies to `line_items`?

2022-04-14 20:20 UTC, traci707 commented
@valentindellangela Can you look at my changes?

2022-04-20 06:17 UTC, slsriehl commented on reference/checkouts.v3.yml
> +    name: API Key
based on the endpoints, this looks like a store-management API. if that's true, the OAuth stuff needs to go back in, and the access_token gets passed as the X-Auth-Token.

```suggestion
    name: X-Auth-Token
```

2022-04-20 06:19 UTC, slsriehl requested changes
looks like the auth section may need to be cleaned up. depending on the rest of the file, this may be duplication that's correctly removed. please confirm and take appropriate action, if any.

@traci707

2022-04-21 16:03 UTC, markcmurphy approved these changes

2022-04-21 16:03 UTC, merged