Devdocs 4182 - Orders V3
bigcommerce/api-specs pull request #828
Opened 2022-06-20 17:16 UTC by bc-tgomez

# [DEVDOCS-4182](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4182)

## Orders v3 YAML malformed 503 response description
* Correct 503 response in Orders v3

2022-06-20 17:28 UTC, traci707 reviewed
Looks good, I don't see an error for the 503 response but there is an error further down on line 733.  I don't know if it is related or not.

2022-06-20 18:33 UTC, traci707 submitted a review, later dismissed

2022-06-24 07:37 UTC, slsriehl commented on reference/orders.v3.yml
> +          description: "All failure response. \nHTTP status code for the entire batch request to roll up to the most severe individual failure to the whole request."
```suggestion
          description: "All <<what?>> failed. \nThe HTTP status code for the entire batch request rolls the most severe individual failure up to the whole request."
```
I'm not sure what this means. Rolls up? is this a directional/spatial metaphor for data/error flow?

2022-06-24 07:38 UTC, slsriehl requested changes
see comment.

2022-06-24 18:41 UTC, bc-tgomez commented
> 

Many thanks @slsriehl for the feedback!

2022-06-24 21:56 UTC, slsriehl approved these changes
excellent.

2022-06-24 22:12 UTC, merged