DEVDOCS-4121 store logs
bigcommerce/api-specs pull request #841
Opened 2022-06-22 16:00 UTC by bc-andreadao

# [DEVDOCS-4121](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4121)

New api specs for Store Logs API

This PR is related to [PR 1547](https://github.com/bigcommerce/dev-docs/pull/1547) (api doc) and [PR 118](https://github.com/bigcommerce-labs/next-dev-center-prototype/pull/118) (redirects)

2022-06-22 17:49 UTC, bc-andreadao commented on reference/store_logs.v3.yml
> +              - inventory
@bookernath Where can I find a list of all the modules? The ones I listed here are from my sandbox store, but was hoping to tell developers all the other types that they can query for. I found some on the UI (screenshot), though I realized the UI display term didn't always match the query term that developers can use.
![Type](https://user-images.githubusercontent.com/96258747/175103152-d05b5e9f-b92d-4cf2-b45b-2fd3dc11fa1c.png)

2022-07-29 20:45 UTC, bc-andreadao commented
The commit SHA-5ca1d613075ad9e9dddd760542599281cf5f15e5 changes enum values to example values. It renders fine in Stoplight, but gives an error (see screenshot). Was hoping we could ignore the failed check in Github.

![stoplight errors](https://user-images.githubusercontent.com/96258747/181840192-44c32dbf-5156-46ac-92a4-ca935935fa15.png)

2022-08-06 19:28 UTC, slsriehl commented
@bc-andreadao what's the reason to change `enum` to `examples`? are they not actually [enums](https://swagger.io/docs/specification/data-models/enums/) (a discrete list of all possible/allowed values)? 

If they aren't enums and you want them to appear as pictured, see what happens when you add a `description` property to the schema object itself.

> The commit [5ca1d61](https://github.com/bigcommerce/api-specs/commit/5ca1d613075ad9e9dddd760542599281cf5f15e5) changes enum values to example values. It renders fine in Stoplight, but gives an error (see screenshot). Was hoping we could ignore the failed check in Github.
> 
> ![stoplight errors](https://user-images.githubusercontent.com/96258747/181840192-44c32dbf-5156-46ac-92a4-ca935935fa15.png)

2022-08-06 19:29 UTC, slsriehl requested changes
see previous comment. This is close!

2022-08-08 17:48 UTC, bc-andreadao commented
It is actually an enum in that it is a discrete list of values (so I changed it back to enum. One thing is that I was not able to get my hands on all possible values, but hopefully that is okay

2022-08-19 17:00 UTC, stanzikratelbc reviewed
@bc-andreadao Hi Andrea, I left some comments about updating the descriptions and possibly adding a description for parameters that currently don't have one.

2022-08-19 21:00 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        * For more information on Authenticating BigCommerce APIs, see: [Authentication](/api-docs/getting-started/authentication).
```suggestion
        * For example request and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/api-docs/getting-started/authentication#x-auth-token-header-example-requests).
```

2022-08-19 21:03 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        |  **UI Name** | **Permission** | **Parameter** |
```suggestion
        |  UI Name | Permission | Parameter |
```

2022-08-19 21:04 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        | --- | --- | --- |
```suggestion
        | :-------|:-----------|:----------|
```

2022-08-19 21:04 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        |Header|Parameter|Description|
```suggestion
        | Header | Parameter | Description |
```

2022-08-19 21:05 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        |-|-|-|
```suggestion
         |:-------|:----------|:------------|
```

2022-08-19 21:06 UTC, slsriehl commented on reference/store_logs.v3.yml
> +        |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|
```suggestion
        | `X-Auth-Token` | `access_token` | Obtained by [creating an API account](/api-docs/getting-started/authentication/rest-api-authentication) or installing an app in a BigCommerce control panel. |
```

2022-08-19 21:32 UTC, slsriehl approved these changes
🎉

2022-08-19 21:34 UTC, merged